name: Build and Push Email Service
run-name: Build and Push Email Service Image to Registry

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  email-build:
    name: Build and push Email Service
    runs-on: arc-runner-set
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Check for changes
        id: email-service-changes
        uses: tj-actions/changed-files@v47.0.1
        with:
          files: |
            email-service/**
      -
        name: Get short commit hash
        if: >-
          ${{ steps.email-service-changes.outputs.any_changed == 'true'
            || github.event_name == 'workflow_dispatch'
          }}
        id: short-sha
        run: |
          echo SHORT_SHA=$(echo $GITHUB_SHA | cut --characters 1-7) >> $GITHUB_OUTPUT
      -
        name: Login to registry
        if: >-
          ${{ steps.email-service-changes.outputs.any_changed == 'true'
            || github.event_name == 'workflow_dispatch'
          }}
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Setup buildx
        if: >-
          ${{ steps.email-service-changes.outputs.any_changed == 'true'
            || github.event_name == 'workflow_dispatch'
          }}
        uses: docker/setup-buildx-action@v3.12.0
      -
        name: Build image
        if: >-
          ${{ steps.email-service-changes.outputs.any_changed == 'true'
            || github.event_name == 'workflow_dispatch'
          }}
        uses: docker/build-push-action@v6.18.0
        env:
          SHORT_SHA: ${{ steps.short-sha.outputs.SHORT_SHA }}
        with:
          context: email-service
          push: true
          tags: ${{ vars.REGISTRY_URL }}/handshake/email-service:${{ env.SHORT_SHA }}
      -
        name: Inform build skipped
        if: steps.email-service-changes.outputs.any_changed == 'false'
        run: |
          echo "No changes to email-service, build skipped!"

  update-infra:
    name: Make changes to infra
    needs:
      - email-build
    if: >-
      ${{ needs.email-build.outputs.files-changed == 'true'
        || github.event_name == 'workflow_dispatch'
      }}
    runs-on: arc-runner-set
    steps:
      -
        name: Checkout infra code
        uses: actions/checkout@v4
        with:
          repository: gagahsyuja/handshake-infra
          ref: master
          persist-credentials: true
          token: ${{ secrets.INFRA_TOKEN }}
      -
        name: Update image tag
        uses: mikefarah/yq@v4
        with:
          cmd: >-
            yq
            --inplace
            --output-format yaml
            '.emailService.image.tag = "${{ needs.email-build.outputs.short-sha }}"'
            values/values-development.yaml
      -
        name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        env:
          SHORT_SHA: ${{ needs.email-build.outputs.short-sha }}
          COMMIT_URL: ${{ format('gagahsyuja/handshake@{0}', needs.email-build.outputs.short-sha) }}
        with:
          repository: .
          commit_message: "Update email-service image tag to `${{ env.SHORT_SHA}}`, ${{ env.COMMIT_URL }}"
          skip_push: false
