name: Build and Push Frontend
run-name: Build and Push Frontend Image to Registry

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  frontend-build:
    name: Build and push frontend
    runs-on: arc-runner-set
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Check for changes
        id: frontend-changes
        uses: tj-actions/changed-files@v47.0.1
        with:
          files: |
            frontend/**
      -
        name: Get short commit hash
        if: >-
          ${{ steps.frontend-changes.outputs.any_changed == 'true'
            || github.event_name == 'workflow_dispatch'
          }}
        id: short-sha
        run: |
          echo SHORT_SHA=$(echo $GITHUB_SHA | cut --characters 1-7) >> $GITHUB_OUTPUT
      -
        name: Login to registry
        if: >-
          ${{ steps.frontend-changes.outputs.any_changed == 'true'
            || github.event_name == 'workflow_dispatch'
          }}
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Setup buildx
        if: >-
          ${{ steps.frontend-changes.outputs.any_changed == 'true'
            || github.event_name == 'workflow_dispatch'
          }}
        uses: docker/setup-buildx-action@v3.12.0
      -
        name: Build image
        if: >-
          ${{ steps.frontend-changes.outputs.any_changed == 'true'
            || github.event_name == 'workflow_dispatch'
          }}
        uses: docker/build-push-action@v6.18.0
        env:
          SHORT_SHA: ${{ steps.short-sha.outputs.SHORT_SHA }}
        with:
          context: frontend
          push: true
          tags: ${{ vars.REGISTRY_URL }}/handshake/frontend:${{ env.SHORT_SHA }}
      -
        name: Inform build skipped
        if: steps.frontend-changes.outputs.any_changed == 'false'
        run: |
          echo "No changes to frontend, build skipped!"
